/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 *
 * @author Reyn
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.awt.*;
import javax.swing.*;

public class Gui extends javax.swing.JFrame {

    int i = 0;
    int value;
    Timer t;
    Timer a;
    Timer updater;
    int updatercounter;
    int count = 0;
    int delay = 1000;
    boolean stopper = false;
    boolean clicker = false;
    int x = 0;
    int y = 0;
    int pl = 0;

    /**
     * Creates new form Gui
     */
    public Gui() {

        BlackJack func = new BlackJack();
        initComponents();

        jLabel23.setVisible(true);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jPanel3.setOpaque(false);
        jPanel5.setOpaque(false);
        jPanel6.setOpaque(false);
        BlackJack Init = new BlackJack();
        Authentication auth = new Authentication();
        BlackJackFunction bjfunc = new BlackJackFunction();
        bjfunc.read_deck_from_txt();
        bjfunc.shuffle();
        auth.update(func.one, func.two, func.three, func.four, func.Dealer);
        value = (func.one.exp * 100) / (func.one.requirement);
        jLabel8.setText(String.valueOf(func.one.Money));
        jProgressBar1.setValue(value);
        jProgressBar1.setToolTipText("Level: " + String.valueOf(func.one.level));
        jLabel18.setText(func.one.Status);
        jLabel19.setText(func.two.Status);
        jLabel20.setText(func.three.Status);
        jLabel21.setText(func.four.Status);
        jLabel22.setText(func.Dealer.Status);
        clicker = false;
        jPanel9.setVisible(false);
        jLabel8.setText("$: " + String.valueOf(func.one.Money));

        getbase();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        Dealers = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setOpaque(false);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 34, 34));
        jLabel6.setText("Lorem Espum");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel13.setBackground(new java.awt.Color(43, 53, 62));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Latest Draw");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, 240, -1));

        jPanel11.setBackground(new java.awt.Color(26, 115, 232));
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 240, 5));

        jPanel12.setBackground(new java.awt.Color(26, 115, 232));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("0");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 29, 30));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel14.setBackground(new java.awt.Color(244, 244, 244));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(33, 33, 33));
        jLabel30.setText("Rounds");
        jPanel14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(33, 33, 33));
        jLabel29.setText("Money");
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(33, 33, 33));
        jLabel31.setText("Busted");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(33, 33, 33));
        jLabel32.setText("Wins");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(33, 33, 33));
        jLabel33.setText("Lose");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(33, 33, 33));
        jLabel34.setText("Hits Count");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(33, 33, 33));
        jLabel35.setText("Hold Counts");
        jPanel14.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(33, 33, 33));
        jLabel36.setText("Double Count");
        jPanel14.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(33, 33, 33));
        jLabel37.setText("Current Bet");
        jPanel14.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(33, 33, 33));
        jLabel38.setText("Username");
        jPanel14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(33, 33, 33));
        jLabel52.setText("jLabel29");
        jPanel14.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel51.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(33, 33, 33));
        jLabel51.setText("jLabel29");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel53.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(33, 33, 33));
        jLabel53.setText("jLabel31");
        jPanel14.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel54.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(33, 33, 33));
        jLabel54.setText("jLabel32");
        jPanel14.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel55.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(33, 33, 33));
        jLabel55.setText("jLabel33");
        jPanel14.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel56.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(33, 33, 33));
        jLabel56.setText("jLabel34");
        jPanel14.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel57.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(33, 33, 33));
        jLabel57.setText("jLabel35");
        jPanel14.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel58.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(33, 33, 33));
        jLabel58.setText("jLabel36");
        jPanel14.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel59.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(33, 33, 33));
        jLabel59.setText("jLabel37");
        jPanel14.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel50.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(33, 33, 33));
        jLabel50.setText("jLabel38");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel10.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, 210));

        jTextArea1.setBackground(new java.awt.Color(244, 244, 244));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 180));

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 20, -1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Butt.png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Butt.png"))); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Butt.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Butt.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Butt.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 100, 20));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 100, 20));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 265, 100, 20));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 20));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 20, 20));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 20, 20));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 20, 20));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 20, 20));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 20, 20));

        jPanel21.setOpaque(false);
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 170, 50));
        jPanel21.getAccessibleContext().setAccessibleParent(jPanel8);

        jPanel20.setOpaque(false);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 140, 100));

        jPanel19.setOpaque(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 180, 100));

        jPanel17.setOpaque(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 190, 100));

        jPanel16.setOpaque(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 200, 100));

        jPanel15.setOpaque(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 110));

        Dealers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/table.png"))); // NOI18N
        Dealers.setToolTipText("");
        jPanel2.add(Dealers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -351, 780, 1110));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setOpaque(false);
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 50));

        jProgressBar1.setBackground(new java.awt.Color(23, 23, 23));
        jProgressBar1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(103, 65, 114));
        jProgressBar1.setToolTipText("0");
        jProgressBar1.setValue(10);
        jProgressBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 13, -1, -1));

        jLabel8.setBackground(new java.awt.Color(30, 30, 30));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, 30));

        jTextField3.setBackground(new java.awt.Color(23, 23, 23));
        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 3, 30));

        jTextField1.setBackground(new java.awt.Color(23, 23, 23));
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, 3));

        jPanel7.setBackground(new java.awt.Color(25, 25, 25));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/table.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        if (clicker == true) {
            refresh();
            BlackJackFunction Bjfunc = new BlackJackFunction();
            BlackJack func = new BlackJack();
            Bjfunc.Phase1(func.one, jLabel1, jLabel18, jPanel15, func.one.getCard(), "Easy");
            status(jLabel24);
            phase2();
            refresh();
        } else {
            System.out.print("Im not clickable");
        }

    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        jPanel9.setVisible(false);
        this.setSize(756, 510);
        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        BlackJack func = new BlackJack();
        this.setVisible(false);
        setData(func.one);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        BlackJack func = new BlackJack();
        this.setVisible(false);
        setData(func.two);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        BlackJack func = new BlackJack();
        this.setVisible(false);
        setData(func.three);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        BlackJack func = new BlackJack();
        this.setVisible(false);
        setData(func.four);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        BlackJack func = new BlackJack();
        this.setVisible(false);
        setData(func.Dealer);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
        if (clicker == true) {
            BlackJackFunction bjfunc = new BlackJackFunction();
            BlackJack func = new BlackJack();
            func.one.awareness = false;
            bjfunc.Hold(func.one);
            phase2();
            jLabel18.setText(func.one.Status);
            func.one.addexp(10);
            status(jLabel24);
            refresh();
        } else {
            System.out.print("Im not clickable");
        }
    }//GEN-LAST:event_jPanel21MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
        BlackJack func = new BlackJack();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "You'll lose your bet if you quit while playing", "Warning", dialogButton);
        if (dialogResult == 0) {
            func.one.Money -= func.one.Bet;
            Tablepick table = new Tablepick();
            table.setVisible(true);
            reset();
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_jPanel22MouseClicked
    int k = 0;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register regform = new Register();
                new Gui().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dealers;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    public void getbase() {
        BlackJackFunction bfunc = new BlackJackFunction();
        BlackJack func = new BlackJack();
        i = 0;
        k = 0;
        func.one.Status = "Ready";
        func.two.Status = "Base";
        func.three.Status = "Base";
        func.four.Status = "Base";
        func.Dealer.Status = "Base";
        t = new Timer(func.one.GameSpeed, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (k == 0) {
                    stopper = true;
                    bfunc.Hits(func.one);
                    Card asd = new Card(jPanel15);
                    asd.DrawImage(func.one.x, 0, func.one.getCard());
                    status(jLabel24);
                    jLabel1.setText(String.valueOf(func.getrawSum(func.one)));
                    jLabel18.setText(func.one.Status);
                    func.callupindex(func.one);
                    refresh();
                } else if (k == 1) {
                    status(jLabel25);
                    bfunc.Hits(func.two);
                    Card asd = new Card(jPanel16);
                    asd.DrawImage(func.two.x, 0, func.two.getCard());
                    jLabel2.setText(String.valueOf(func.getrawSum(func.two)));
                    jLabel19.setText(func.two.Status);
                    func.callupindex(func.two);
                    refresh();
                } else if (k == 2) {
                    status(jLabel26);
                    bfunc.Hits(func.three);
                    Card asd = new Card(jPanel17);
                    asd.DrawImage(func.three.x, 0, func.three.getCard());
                    jLabel3.setText(String.valueOf(func.getrawSum(func.three)));
                    jLabel20.setText(func.two.Status);
                    func.callupindex(func.three);
                    refresh();
                } else if (k == 3) {
                    status(jLabel27);
                    bfunc.Hits(func.four);
                    Card asd = new Card(jPanel20);
                    asd.DrawImage(func.four.x, 0, func.four.getCard());
                    jLabel4.setText(String.valueOf(func.getrawSum(func.four)));
                    jLabel21.setText(func.four.Status);
                    func.callupindex(func.four);

                    refresh();
                } else if (k == 4) {
                    i++;
                    status(jLabel23);
                    bfunc.Hits(func.Dealer);
                    Card asd = new Card(jPanel19);
                    if (i == 1) {
                        asd.DrawImage(func.Dealer.x, 0, func.Dealer.getCard());
                    } else {
                        asd.DrawImage(func.Dealer.x, 0, "back.jpg");
                    }

                    func.getrawSum(func.Dealer);
                    jLabel5.setText(String.valueOf(func.getDealerSum(func.Dealer)));
                    func.callupindex(func.Dealer);
                    jLabel22.setText(func.Dealer.Status);
                    refresh();
                    if (i == 1) {
                        k = -1;
                    } else {
                        clicker = true;
                        stopper = false;
                        refresh();
                        bfunc.CheckBlackJack(func.one);
                        bfunc.CheckBlackJack(func.two);
                        bfunc.CheckBlackJack(func.three);
                        bfunc.CheckBlackJack(func.four);
                        if (func.Dealer.Status.equalsIgnoreCase("BlackJack")) {
                            ProceedWin();
                        } else {
                            func.Dealer.Status = "Ready";
                            func.Dealer.notbj();
                        }
                        if (func.one.Status.equalsIgnoreCase("BlackJack")) {
                            func.one.Status = "BlackJack";
                        } else {
                            func.one.Status = "Ready";
                            func.one.notbj();
                        }
                        if (func.two.Status.equalsIgnoreCase("BlackJack")) {
                            func.two.Status = "BlackJack";
                        } else {
                            func.two.Status = "Ready";
                            func.two.notbj();
                        }
                        if (func.three.Status.equalsIgnoreCase("BlackJack")) {
                            func.three.Status = "BlackJack";
                        } else {
                            func.three.Status = "Ready";
                            func.three.notbj();
                        }
                        if (func.four.Status.equalsIgnoreCase("BlackJack")) {
                            func.four.Status = "BlackJack";
                        } else {
                            func.four.Status = "Ready";
                            func.four.notbj();
                        }

                        func.Dealer.Status = "Ready";
                        refresh();
                        t.stop();

                    }
                }

                k++;
            }
        });

        t.start();

        stopper = false;
    }

    public void phase2() {

        BlackJackFunction bfunc = new BlackJackFunction();
        BlackJack func = new BlackJack();
        Authentication auth = new Authentication();
        clicker = false;
        int sum;
        a = new Timer(func.one.GameSpeed, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (k == 0) {
                    refresh();
                    if (func.Dealer.Status.equalsIgnoreCase("Busted")) {
                        ProceedWin();
                    } else if (func.two.Status.equalsIgnoreCase("Ready")) {
                        bfunc.Phase1(func.two, jLabel2, jLabel19, jPanel16, func.two.getCard(), "Easy");

                        if (func.three.Status.equalsIgnoreCase("Ready")) {
                            status(jLabel25);
                        }
                    } else {
                        k = 1;
                    }
                }
                if (k == 1) {
                    refresh();
                    if (func.three.Status.equalsIgnoreCase("Ready")) {
                        bfunc.Phase1(func.three, jLabel3, jLabel20, jPanel17, func.three.getCard(), "Easy");
                        if (func.four.Status.equalsIgnoreCase("Ready")) {
                            status(jLabel26);
                        }
                    } else {
                        k = 2;
                    }
                }
                if (k == 2) {
                    refresh();
                    if (func.four.Status.equalsIgnoreCase("Ready")) {
                        bfunc.Phase1(func.four, jLabel4, jLabel21, jPanel20, func.four.getCard(), "Easy");
                        if (func.Dealer.Status.equalsIgnoreCase("Ready")) {
                            status(jLabel27);
                        }
                    } else {
                        k = 3;
                    }
                }
                if (k == 3) {
                    refresh();
                    if (func.Dealer.Status.equalsIgnoreCase("Ready")) {
                        bfunc.Phase1(func.Dealer, Dealers, jLabel22, jPanel19, "back.jpg", "Easy");
                        if (func.one.Status.equalsIgnoreCase("Ready")) {
                            status(jLabel23);
                        }
                    } else {
                        k = 4;
                    }
                }
                if (k == 4) {
                    refresh();
                    if (func.one.awareness == false) {
                        if (func.two.Status.equalsIgnoreCase("Ready") || func.three.Status.equalsIgnoreCase("Ready")
                                || func.four.Status.equalsIgnoreCase("Ready") || func.Dealer.Status.equalsIgnoreCase("Ready")) {
                            System.out.println("Table turn!");
                            k = -1;
                        } else {
                            ProceedWin();

                        }
                    } else {
                        clicker = true;

                    }

                }

                k++;
            }
        });

        a.start();

        k = 0;

    }

    public void reset() {
        BlackJackFunction bjfunc = new BlackJackFunction();
        BlackJack func = new BlackJack();
        bjfunc.reset(func.one);
        bjfunc.reset(func.two);
        bjfunc.reset(func.three);
        bjfunc.reset(func.four);
        bjfunc.reset(func.Dealer);
        func.one.awareness = true;
        BetEasy[] asd = new BetEasy[5];
        asd[0] = new BetEasy();
        asd[0].setVisible(true);
        this.dispose();
    }

    public void status(javax.swing.JLabel as) {
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        as.setVisible(true);
    }

    public void phase3() {

        Timer b;
        BlackJackFunction bfunc = new BlackJackFunction();
        BlackJack func = new BlackJack();
        Authentication auth = new Authentication();
        clicker = false;
        int sum;
        Card asd = new Card(jPanel19);
        try {
            refresh();
            asd.DrawImage(0, 0, func.Dealer.Card[0][3]);
            asd.DrawImage(15, 0, func.Dealer.Card[1][3]);
            asd.DrawImage(30, 0, func.Dealer.Card[2][3]);
            asd.DrawImage(45, 0, func.Dealer.Card[3][3]);
        } catch (Exception ex) {

        }

        b = new Timer(func.one.GameSpeed, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (pl == 0) {
                    refresh();

                    jLabel18.setText(func.one.Status);
                }
                if (pl == 1) {
                    jLabel19.setText(func.two.Status);
                }
                if (pl == 2) {
                    jLabel20.setText(func.three.Status);
                }
                if (pl == 3) {
                    jLabel21.setText(func.four.Status);
                    auth.update(func.one, func.two, func.three, func.four, func.Dealer);
                }
                if (pl == 4) {
                    System.out.println("Shall reset in 3 sec");
                }
                if (pl == 5) {

                }
                if (pl == 6) {

                }
                if (pl == 7) {

                    reset();

                }

                pl++;
            }
        });

        b.start();

        pl = 0;

    }

    public void ProceedWin() {
        BlackJackFunction bfunc = new BlackJackFunction();
        BlackJack func = new BlackJack();
        Authentication auth = new Authentication();
        jLabel5.setText(String.valueOf(func.Dealer.sum));
        bfunc.Winner(func.one, func.Dealer);
        bfunc.Winner(func.two, func.Dealer);
        bfunc.Winner(func.three, func.Dealer);
        bfunc.Winner(func.four, func.Dealer);
        auth.update(func.one, func.two, func.three, func.four, func.Dealer);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        phase3();

    }

    public void updated(Players z) {
        BlackJack func = new BlackJack();
        updater = new Timer(func.one.GameSpeed, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (updatercounter == 0) {
                    setData(z);
                }
                if (updatercounter == 1) {
                    setData(z);
                }
                if (updatercounter == 2) {
                    setData(z);
                }
                if (updatercounter == 3) {
                    setData(z);
                }
                if (updatercounter == 4) {
                    setData(z);
                }
                if (updatercounter == 5) {
                    setData(z);
                }
                if (updatercounter == 6) {
                    setData(z);
                }
                if (updatercounter == 7) {
                    setData(z);
                    updatercounter = 0;

                }

                updatercounter++;
            }
        });

        updater.start();

        updatercounter = 0;
    }

    public void setData(Players z) {

        BlackJack func = new BlackJack();

        this.setSize(1016, 510);
        this.setLocationRelativeTo(null);
        jPanel9.setVisible(true);
        this.setVisible(true);
        jLabel9.setText(String.valueOf(z.level));
        jLabel6.setText(z.Username);
        jLabel50.setText(z.Username);
        jLabel51.setText(String.valueOf(z.Money));
        jLabel52.setText(String.valueOf(z.Rounds));
        jLabel53.setText(String.valueOf(z.Busted));
        jLabel54.setText(String.valueOf(z.Wins));
        jLabel55.setText(String.valueOf(z.Lose));
        jLabel56.setText(String.valueOf(z.HitsCount));
        jLabel57.setText(String.valueOf(z.HoldsCount));
        jLabel58.setText(String.valueOf(z.DoubleCount));
        jLabel59.setText(String.valueOf(z.Bet));
        String ilabasmo;
        for (int i = 9; i != 0; i--) {
            ilabasmo = z.Logs[i];
            if (ilabasmo.equalsIgnoreCase("Null")) {

            } else {
                jTextArea1.append(z.Logs[i] + "\n");
            }

        }

    }

    public void refresh() {
        Authentication auth = new Authentication();
        BlackJack func = new BlackJack();
        BlackJackFunction bjfunc = new BlackJackFunction();
        bjfunc.setSum(jLabel1);
        jLabel1.setText(String.valueOf(func.one.sum));
        jLabel2.setText(String.valueOf(func.two.sum));
        jLabel3.setText(String.valueOf(func.three.sum));
        Dealers.setText(String.valueOf(func.Dealer.sum));
        jLabel4.setText(String.valueOf(func.four.sum));
        value = (func.one.exp * 100) / (func.one.requirement);
        jProgressBar1.setToolTipText("Level: " + String.valueOf(func.one.level));
        jLabel8.setText("$: " + String.valueOf(func.one.Money));
        jProgressBar1.setValue(value);
        auth.update(func.one, func.two, func.three, func.four, func.Dealer);
        jLabel18.setText(func.one.Status);
        jLabel19.setText(func.two.Status);
        jLabel20.setText(func.three.Status);
        jLabel21.setText(func.four.Status);
        jLabel22.setText(func.Dealer.Status);
        jPanel18.setVisible(false);
        jPanel18.setVisible(true);

    }
}
